# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Python image that includes hatchling
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy the necessary files
COPY pyproject.toml README.md /app/

# Install the project's dependencies
RUN pip install hatchling

# Use hatchling to build the project
RUN hatch build

# Install the built project
RUN pip install .

# Expose necessary environment variables for LogSeq API
ENV LOGSEQ_API_TOKEN=your_token_here
ENV LOGSEQ_API_URL=http://localhost:12315

# Set the entrypoint to the MCP server script
ENTRYPOINT ["mcp-logseq"]
